# 基础设置
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
mode: Rule
allow-lan: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  ASN.mmdb: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
unified-delay: true
tcp-concurrent: true
log-level: silent
find-process-mode: always
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
#面板默认 Meta 可选 Yacd / Zash 重启模块即可加载
external-ui: /data/adb/box_bll/panel/Meta/
secret: ""
# —————————
#####################
#修改配置文件保存时，建议重启服务/重载配置.
#####################

# 健康检查
p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
# —————————

# 订阅地址相关
A: &A
  filter: "^(?!.*(套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网)).*$"
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址

All: &All
  type: url-test
  use:
  - 1.主要地址
  - 2.备用地址
  - 3.额外地址

proxy-providers: # ← 此函数位置请勿变动！此为模块更新时备份恢复订阅变量范围 ↓
  1.主要地址:
    <<: *p
    url: "https://45.137.181.206/api/v1/client/subscribe?token=2930524bfb1ce8788d43156d588fb0c0"
    
  2.备用地址:
    <<: *p
    url: "引入您的Clash订阅链接地址"
  
  3.额外地址:
    <<: *p
    url: "引入您的Clash订阅链接地址"
# —————————

# 节点记忆
profile: # ← 此函数位置请勿变动！此为模块更新时备份恢复订阅变量范围 ↑
  store-selected: true
  store-fake-ip: true
# —————————

# 嗅探模块
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
# —————————

# 网卡模块
tun:
  enable: true #true 开 #false 关
  device: meta
  stack: gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  udp-timeout: 300
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  route-exclude-address:
  - 192.168.0.0/16
  - fc00::/7
  exclude-package: # 游戏卡顿可添加包名 仅Android
    #- com.tencent.tmgp.sgame
# —————————

# DNS模块
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "connect.rom.miui.com"
    - "localhost.ptlogin2.qq.com"
    - "+.market.xiaomi.com"
  direct-nameserver:
    - 119.29.29.29
    - 1.12.12.12
    - 223.5.5.5
    - 223.6.6.6
  proxy-server-nameserver:
    - 119.29.29.29
    - 1.12.12.12
    - 223.5.5.5
    - 223.6.6.6
  nameserver-policy:
    "RULE-SET:CN_域名,CN_IP":
      - https://doh.pub/dns-query#🌎 全球直连
      - https://dns.alidns.com/dns-query#🌎 全球直连
  nameserver:
    - https://dns.google/dns-query#🌐 DNS解析
    - https://cloudflare-dns.com/dns-query#🌐 DNS解析
# —————————

proxies:
  - {name: 🌎 全球直连, type: direct, udp: true}
  - {name: ⛔️ 拒绝连接, type: reject}
  - {name: 🌐 DNS_Hijack, type: dns}

proxy_groups: &proxy_groups
    type: select
    proxies:
      - 🎯 总模式
      - ⛔️ 拒绝连接
      - ♻️ 延迟最低
      - ♻️ 故障转移
      - ♻️ 负载均衡
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韓國节点
      - 💎 专线节点
      - 🌍 其它地区
      - 🌎 全球直连
    <<: *A
# —————————
proxy-groups:
  - name: 🎯 总模式
    type: select
    proxies:
      - ♻️ 延迟最低
      - ♻️ 故障转移
      - ♻️ 负载均衡
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韓國节点
      - 💎 专线节点
      - 🌍 其它地区
      - 🌎 全球直连
# —————————

  - name: ♻️ 延迟最低
    type: url-test
    proxies:
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韓國节点

  - name: ♻️ 故障转移
    type: fallback
    <<: *A

  - name: ♻️ 负载均衡
    type: load-balance
    strategy: round-robin
    <<: *A

  - name: 🌐 DNS解析
    <<: *proxy_groups

  - name: 📲 电报信息
    <<: *proxy_groups

  - name: 🤖 OpenAI
    <<: *proxy_groups

  - name: 🎮 Discord
    <<: *proxy_groups

  - name: 📸 TikTok
    <<: *proxy_groups

  - name: 🎬 油管媒体
    <<: *proxy_groups

  - name: 📹 奈飞媒体
    <<: *proxy_groups

  - name: 📱 脸书社交
    <<: *proxy_groups

  - name: 📣 谷歌推送
    <<: *proxy_groups

  - name: 📢 谷歌服务
    <<: *proxy_groups

  - name: Ⓜ️ 微软服务
    <<: *proxy_groups

  - name: 🍎 苹果服务
    <<: *proxy_groups

  - name: 🛑 广告拦截
    type: select
    proxies:
      - ⛔️ 拒绝连接
      - 🌎 全球直连
      - REJECT-DROP
      - PASS #匹配规则

  - name: 🐋 漏网之鱼
    <<: *proxy_groups

  - name: 💎 专线节点
    filter: "^(?=.*(专线|HOME)).*$"
    <<: *All

  - name: 🇭🇰 香港节点
    filter: "^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong))^(?!.*(专线|HOME)).*$"
    <<: *All

  - name: 🇯🇵 日本节点
    filter: "^(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan))^(?!.*(专线|HOME)).*$"
    <<: *All

  - name: 🇺🇲 美国节点
    filter: "^(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^(?!.*(专线|HOME)).*$"
    <<: *All

  - name: 🇨🇳 台湾节点
    filter: "^(?=.*(台|新北|彰化|TW|Taiwan))^(?!.*(专线|HOME)).*$"
    <<: *All

  - name: 🇸🇬 狮城节点
    filter: "^(?=.*(新加坡|坡|狮城|SG|Singapore))^(?!.*(专线|HOME)).*$"
    <<: *All

  - name: 🇰🇷 韓國节点
    filter: "^(?=.*(韓國))^(?!.*(专线|HOME)).*$"
    <<: *All
    
  - name: 🌍 其它地区
    filter: "^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|灾|网易|Netease|套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网))^(?!.*(专线|HOME)).*$"
    <<: *All
# —————————

rule-anchor:
  RuleDefault: &RuleDefault
    {type: http, behavior: classical, format: text, interval: 86400}
# —————————

rule-providers:
  CN_IP:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/cn.list"

  private_Lan:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/classical/private.list"

  CN_域名:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/cn.list"

  anti-ads-all:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt"

  TikTok:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list"

  Facebook:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list"

  Telegram:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list"

  YouTube:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list"

  Google:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list"

  GoogleFCM:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list"

  Microsoft:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list"

  Apple:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list"

  OpenAI:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list"

  Netflix:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list"

  Discord:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Discord/Discord.list"
# —————————

rules:
  - DST-PORT,53,🌐 DNS_Hijack
  - RULE-SET,anti-ads-all,🛑 广告拦截
  - RULE-SET,Discord,🎮 Discord
  - RULE-SET,TikTok,📸 TikTok
  - RULE-SET,YouTube,🎬 油管媒体
  - RULE-SET,Netflix,📹 奈飞媒体
  - RULE-SET,Facebook,📱 脸书社交
  - RULE-SET,OpenAI,🤖 OpenAI
  - RULE-SET,GoogleFCM,📣 谷歌推送
  - RULE-SET,Google,📢 谷歌服务
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,Microsoft,Ⓜ️ 微软服务
  - RULE-SET,Telegram,📲 电报信息
  - RULE-SET,CN_域名,🌎 全球直连
  - RULE-SET,CN_IP,🌎 全球直连
  - RULE-SET,private_Lan,🌎 全球直连,no-resolve
  - MATCH,🐋 漏网之鱼
# —————————
